language: node_js
node_js:
  - "10"

dist: trusty
sudo: required

before_script:
  - npm install -g @angular/cli
  - npm install -g coveralls
script:
  - npm run lint
  - npm run test --verbose
  - npm run build
  - npm run build:demo
after_success:
  - npm run coverall
  - cd dist/lib

deploy:
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    on:
      tags: true
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist/demo-app
    on:
      tags: true
